/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.ClienteController;
import controllers.HabitacionController;
import controllers.MovimientosController;
import controllers.RepClienteController;
import controllers.RepReservasController;
import controllers.RepHabitacionController;
import controllers.RepTrabajadorController;
import controllers.ReservasController;
import controllers.TrabajadorController;

/**
 *
 * @author Diego
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setExtendedState(Menu.MAXIMIZED_BOTH);
        this.setTitle("Sistema de reservas hotel Starlight INN");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        lbl_idTrabajador = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_ape_paterno = new javax.swing.JLabel();
        lbl_ape_materno = new javax.swing.JLabel();
        lbl_acceso = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuClientes = new javax.swing.JMenu();
        clienteMenuItem = new javax.swing.JMenuItem();
        reservasMenuItem = new javax.swing.JMenuItem();
        movimientosMenuItem = new javax.swing.JMenuItem();
        mnuTrabajador = new javax.swing.JMenu();
        trabajadorMenuItem = new javax.swing.JMenuItem();
        mnuHabitaciones = new javax.swing.JMenu();
        habitacionesMenuItem = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        repclientesMenuItem = new javax.swing.JMenuItem();
        represervasMenuItem = new javax.swing.JMenuItem();
        reptrabajadoresMenuItem = new javax.swing.JMenuItem();
        rephabitacionesMenuItem = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(javax.swing.UIManager.getDefaults().getColor("Menu.selectionBackground"));

        lbl_idTrabajador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_idTrabajador.setText("jLabel1");
        escritorio.add(lbl_idTrabajador);
        lbl_idTrabajador.setBounds(20, 20, 210, 15);

        lbl_nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_nombre.setText("jLabel2");
        escritorio.add(lbl_nombre);
        lbl_nombre.setBounds(20, 50, 210, 15);

        lbl_ape_paterno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_ape_paterno.setText("jLabel3");
        escritorio.add(lbl_ape_paterno);
        lbl_ape_paterno.setBounds(20, 80, 210, 15);

        lbl_ape_materno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_ape_materno.setText("jLabel4");
        escritorio.add(lbl_ape_materno);
        lbl_ape_materno.setBounds(20, 110, 210, 15);

        lbl_acceso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_acceso.setText("jLabel5");
        escritorio.add(lbl_acceso);
        lbl_acceso.setBounds(20, 140, 210, 15);

        mnuClientes.setMnemonic('f');
        mnuClientes.setText("Clientes");

        clienteMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        clienteMenuItem.setMnemonic('o');
        clienteMenuItem.setText("Cliente");
        clienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteMenuItemActionPerformed(evt);
            }
        });
        mnuClientes.add(clienteMenuItem);

        reservasMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        reservasMenuItem.setText("Reservas");
        reservasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservasMenuItemActionPerformed(evt);
            }
        });
        mnuClientes.add(reservasMenuItem);

        movimientosMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        movimientosMenuItem.setMnemonic('t');
        movimientosMenuItem.setText("Movimientos");
        movimientosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movimientosMenuItemActionPerformed(evt);
            }
        });
        mnuClientes.add(movimientosMenuItem);

        menuBar.add(mnuClientes);

        mnuTrabajador.setMnemonic('e');
        mnuTrabajador.setText("Trabajador");

        trabajadorMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        trabajadorMenuItem.setMnemonic('s');
        trabajadorMenuItem.setText("Trabajadores y accesos");
        trabajadorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trabajadorMenuItemActionPerformed(evt);
            }
        });
        mnuTrabajador.add(trabajadorMenuItem);

        menuBar.add(mnuTrabajador);

        mnuHabitaciones.setMnemonic('h');
        mnuHabitaciones.setText("Habitaciones");

        habitacionesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        habitacionesMenuItem.setMnemonic('c');
        habitacionesMenuItem.setText("Habitaciones");
        habitacionesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitacionesMenuItemActionPerformed(evt);
            }
        });
        mnuHabitaciones.add(habitacionesMenuItem);

        menuBar.add(mnuHabitaciones);

        mnuReportes.setText("Reportes");

        repclientesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        repclientesMenuItem.setText("Clientes");
        repclientesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repclientesMenuItemActionPerformed(evt);
            }
        });
        mnuReportes.add(repclientesMenuItem);

        represervasMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        represervasMenuItem.setText("Reservas");
        represervasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                represervasMenuItemActionPerformed(evt);
            }
        });
        mnuReportes.add(represervasMenuItem);

        reptrabajadoresMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        reptrabajadoresMenuItem.setText("Trabajadores");
        reptrabajadoresMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reptrabajadoresMenuItemActionPerformed(evt);
            }
        });
        mnuReportes.add(reptrabajadoresMenuItem);

        rephabitacionesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        rephabitacionesMenuItem.setText("Habitaciones");
        rephabitacionesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rephabitacionesMenuItemActionPerformed(evt);
            }
        });
        mnuReportes.add(rephabitacionesMenuItem);

        menuBar.add(mnuReportes);

        mnuSalir.setText("Salir");
        mnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSalirMouseClicked(evt);
            }
        });
        menuBar.add(mnuSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clienteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteMenuItemActionPerformed
        VistaClientes vista = new VistaClientes();
        escritorio.add(vista);
        vista.toFront();
        vista.setVisible(true);
        ClienteController controlador = new ClienteController(vista); 
    }//GEN-LAST:event_clienteMenuItemActionPerformed

    private void trabajadorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trabajadorMenuItemActionPerformed
        VistaTrabajadores vista = new VistaTrabajadores();
        escritorio.add(vista);
        vista.toFront();
        vista.setVisible(true);
        TrabajadorController controlador = new TrabajadorController(vista); 
    }//GEN-LAST:event_trabajadorMenuItemActionPerformed

    private void movimientosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movimientosMenuItemActionPerformed
        VistaMovimientos vista = new VistaMovimientos();
        escritorio.add(vista);
        vista.toFront();
        vista.setVisible(true);
        MovimientosController controlador = new MovimientosController(vista); 
    }//GEN-LAST:event_movimientosMenuItemActionPerformed

    private void reservasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservasMenuItemActionPerformed
        VistaReserva vista = new VistaReserva();
        escritorio.add(vista);
        vista.toFront();
        vista.setVisible(true);
        ReservasController controlador = new ReservasController(vista); 
    }//GEN-LAST:event_reservasMenuItemActionPerformed

    private void mnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_mnuSalirMouseClicked

    private void habitacionesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitacionesMenuItemActionPerformed
        VistaHabitaciones vista = new VistaHabitaciones();
        escritorio.add(vista);
        vista.toFront();
        vista.setVisible(true);
        HabitacionController controlador = new HabitacionController(vista);
    }//GEN-LAST:event_habitacionesMenuItemActionPerformed

    private void reptrabajadoresMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reptrabajadoresMenuItemActionPerformed
        VistaRepTrabajadores vista = new VistaRepTrabajadores();
        escritorio.add(vista);
        vista.toFront();
        vista.setVisible(true);
        RepTrabajadorController controlador = new RepTrabajadorController(vista);
    }//GEN-LAST:event_reptrabajadoresMenuItemActionPerformed

    private void represervasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_represervasMenuItemActionPerformed
        VistaRepReservas vista = new VistaRepReservas();
        escritorio.add(vista);
        vista.toFront();
        vista.setVisible(true);
        RepReservasController controlador = new RepReservasController(vista);
    }//GEN-LAST:event_represervasMenuItemActionPerformed

    private void rephabitacionesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rephabitacionesMenuItemActionPerformed
        VistaRepHabitacion vista = new VistaRepHabitacion();
        escritorio.add(vista);
        vista.toFront();
        vista.setVisible(true);
        RepHabitacionController controlador = new RepHabitacionController(vista);
    }//GEN-LAST:event_rephabitacionesMenuItemActionPerformed

    private void repclientesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repclientesMenuItemActionPerformed
        VistaRepClientes vista = new VistaRepClientes();
        escritorio.add(vista);
        vista.toFront();
        vista.setVisible(true);
        RepClienteController controlador = new RepClienteController(vista);
    }//GEN-LAST:event_repclientesMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem clienteMenuItem;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem habitacionesMenuItem;
    public javax.swing.JLabel lbl_acceso;
    public javax.swing.JLabel lbl_ape_materno;
    public javax.swing.JLabel lbl_ape_paterno;
    public javax.swing.JLabel lbl_idTrabajador;
    public javax.swing.JLabel lbl_nombre;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuClientes;
    public javax.swing.JMenu mnuHabitaciones;
    public javax.swing.JMenu mnuReportes;
    private javax.swing.JMenu mnuSalir;
    public javax.swing.JMenu mnuTrabajador;
    private javax.swing.JMenuItem movimientosMenuItem;
    private javax.swing.JMenuItem repclientesMenuItem;
    private javax.swing.JMenuItem rephabitacionesMenuItem;
    private javax.swing.JMenuItem represervasMenuItem;
    private javax.swing.JMenuItem reptrabajadoresMenuItem;
    private javax.swing.JMenuItem reservasMenuItem;
    private javax.swing.JMenuItem trabajadorMenuItem;
    // End of variables declaration//GEN-END:variables

}
